# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dl4_-LDPUxEi97fNDRzqxh2MTdyxfFGI
"""

import pandas as pd
from google.colab import files
import zipfile
import io

uploaded = files.upload()

# Get the name of the uploaded file
uploaded_file_name = next(iter(uploaded))

if uploaded_file_name.endswith('.zip')
    # If a zip file was uploaded, extract its contents
    with zipfile.ZipFile(io.BytesIO(uploaded[uploaded_file_name]), 'r') as z:
        z.extractall()
    # Assuming 'anemia.csv' is now available in the current directory after extraction
    df = pd.read_csv('anemia.csv')
elif uploaded_file_name.endswith('.csv'):
    # If a CSV file was uploaded directly, read it
    df = pd.read_csv(io.BytesIO(uploaded[uploaded_file_name]))
else:
    raise ValueError(f"Unsupported file type uploaded: '{uploaded_file_name}'. Expected a .zip or .csv file containing 'anemia.csv'.")

df.head()

# Import thư viện cần thiết
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dữ liệu từ Google Sheets CSV link (hoặc tải file CSV)
df = pd.read_csv('anemia.csv')
data = df # Fixed: url was a DataFrame, now data uses the already loaded df

# Kiểm tra dữ liệu
print(data.head())
print(data.info())

# Chia dữ liệu thành features và target
X = data[['Gender', 'Hemoglobin', 'MCH', 'MCHC', 'MCV']]
y = data['Result']

# Chia dữ liệu thành train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import MinMaxScaler

# Khởi tạo MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit scaler trên tập train và transform cả train/test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# In ra kết quả
print("X_train_scaled:\n", X_train_scaled)
print("X_test_scaled:\n", X_test_scaled)

import numpy as np

class LogisticRegressionScratch:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        for _ in range(self.n_iters):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self.sigmoid(linear_model)
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict_proba(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        return self.sigmoid(linear_model)

    def predict(self, X):
        y_predicted = self.predict_proba(X)
        return np.array([1 if i > 0.5 else 0 for i in y_predicted])

import numpy as np

class LinearRegressionScratch:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        for _ in range(self.n_iters):
            y_predicted = np.dot(X, self.weights) + self.bias
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        return np.dot(X, self.weights) + self.bias

from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, f1_score, precision_score, recall_score, confusion_matrix

# Instantiate and train the Linear Regression model
linear_model = LinearRegressionScratch(
    learning_rate=0.01,
    n_iters= 50000
)

linear_model.fit(X_train_scaled, y_train)

y_pred_linear = linear_model.predict(X_test_scaled)


print("Mean Squared Error (Linear Regression):", mean_squared_error(y_test, y_pred_linear))
print("R-squared (Linear Regression):", r2_score(y_test, y_pred_linear))

y_pred_linear_class = [1 if p > 0.5 else 0 for p in y_pred_linear]

print("\nClassification Report (Linear Regression with 0.5 threshold):")
print("Accuracy:", accuracy_score(y_test, y_pred_linear_class))
print("F1 Score:", f1_score(y_test, y_pred_linear_class))
print("Precision:", precision_score(y_test, y_pred_linear_class))
print("Recall:", recall_score(y_test, y_pred_linear_class))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_linear_class))

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Nạp dữ liệu và chuẩn hóa
try:
    # Đảm bảo file tồn tại (đã được upload/giải nén ở các bước trước)
    df_temp = pd.read_csv('anemia.csv')
    X = df_temp[['Gender', 'Hemoglobin', 'MCH', 'MCHC', 'MCV']]
    y = df_temp['Result']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Huấn luyện lại mô hình Logistic Regression từ scratch
    model = LogisticRegressionScratch(learning_rate=0.01, n_iters=50000)
    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)
    print("Đã nạp dữ liệu và huấn luyện xong mô hình Logistic Regression.")
except FileNotFoundError:
    print("Lỗi: Không tìm thấy tệp 'anemia.csv'. Vui lòng chạy lại ô upload/giải nén ở đầu notebook.")

# train Random Forest model
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

# dự đoán
y_pred_rf = rf_model.predict(X_test_scaled)

# đánh giá
print("Accuracy (Random Forest):", accuracy_score(y_test, y_pred_rf))
print("F1 Score (Random Forest):", f1_score(y_test, y_pred_rf))
print("Precision (Random Forest):", precision_score(y_test, y_pred_rf))
print("Recall (Random Forest):", recall_score(y_test, y_pred_rf))

print("\nConfusion Matrix (Random Forest):\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report (Random Forest):\n", classification_report(y_test, y_pred_rf))

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Lấy mức độ quan trọng của các đặc trưng từ Random Forest
importances = rf_model.feature_importances_
feature_names = ['Gender', 'Hemoglobin', 'MCH', 'MCHC', 'MCV']
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Vẽ biểu đồ
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='viridis')
plt.title('Mức độ quan trọng của các chỉ số trong việc dự đoán thiếu máu')
plt.show()

print("Bảng xếp hạng quan trọng:")
print(feature_importance_df)

# Thử nghiệm Logistic Regression với các tham số mới
print("\n--- Logistic Regression với các tham số thay đổi ---")
model_new_lr = LogisticRegressionScratch(
    learning_rate=0.01, # Giảm learning rate
    n_iters=30000     # Giảm số lần lặp
)

model_new_lr.fit(X_train_scaled, y_train)
y_pred_new_lr = model_new_lr.predict(X_test_scaled)

print("Accuracy (New Logistic Regression):", accuracy_score(y_test, y_pred_new_lr))
print("F1 Score (New Logistic Regression):", f1_score(y_test, y_pred_new_lr))
print("Precision (New Logistic Regression):", precision_score(y_test, y_pred_new_lr))
print("Recall (New Logistic Regression):", recall_score(y_test, y_pred_new_lr))
print("Confusion Matrix (New Logistic Regression):\n", confusion_matrix(y_test, y_pred_new_lr))

# Thử nghiệm Linear Regression với các tham số mới
print("\n--- Linear Regression với các tham số thay đổi ---")
linear_model_new_lr = LinearRegressionScratch(
    learning_rate=0.005, # Giảm learning rate
    n_iters=30000         # Giảm số lần lặp
)

linear_model_new_lr.fit(X_train_scaled, y_train)
y_pred_linear_new_lr = linear_model_new_lr.predict(X_test_scaled)

print("Mean Squared Error (New Linear Regression):", mean_squared_error(y_test, y_pred_linear_new_lr))
print("R-squared (New Linear Regression):", r2_score(y_test, y_pred_linear_new_lr))

# Chuyển đổi dự đoán liên tục sang nhãn phân loại (0 hoặc 1)
y_pred_linear_class_new_lr = [1 if p > 0.5 else 0 for p in y_pred_linear_new_lr]

print("Accuracy (New Linear Regression - Threshold 0.5):", accuracy_score(y_test, y_pred_linear_class_new_lr))
print("F1 Score (New Linear Regression - Threshold 0.5):", f1_score(y_test, y_pred_linear_class_new_lr))
# Sửa lỗi: Sử dụng y_pred_linear_class_new_lr thay vì y_pred_linear_new_lr
print("Confusion Matrix (New Linear Regression):\n", confusion_matrix(y_test, y_pred_linear_class_new_lr))

def clinical_scoring_system(row):
    score = 0

    # Kiểm tra Hemoglobin (Trọng số cao nhất)
    if row['Gender'] == 1: # Nam
        if row['Hemoglobin'] < 13.0: score += 3
    else: # Nữ
        if row['Hemoglobin'] < 12.0: score += 3

    # Kiểm tra các chỉ số phụ (Mỗi cái đóng góp 1 phần)
    if row['MCV'] < 80: score += 1
    if row['MCH'] < 27: score += 1
    if row['MCHC'] < 32: score += 1

    # Ngưỡng quyết định tổng hợp
    return 1 if score >= 3 else 0

# Áp dụng thang điểm
data['Scoring_Pred'] = data.apply(clinical_scoring_system, axis=1)

# Đánh giá so với nhãn trong file
from sklearn.metrics import classification_report, confusion_matrix

print("Báo cáo kết quả dựa trên Thang điểm Tổng hợp:")
print(classification_report(data['Result'], data['Scoring_Pred']))

print("\nMa trận nhầm lẫn (Thang điểm vs File):")
print(confusion_matrix(data['Result'], data['Scoring_Pred']))

# Hiển thị các ca mà thang điểm cho kết quả khác với chẩn đoán Hb đơn thuần
data['WHO_Only'] = data.apply(lambda r: 1 if ((r['Gender']==1 and r['Hemoglobin']<13) or (r['Gender']==0 and r['Hemoglobin']<12)) else 0, axis=1)

changed_cases = data[data['Scoring_Pred'] != data['WHO_Only']]
print(f"\nSố ca mà thang điểm tổng hợp thay đổi quyết định so với chỉ dùng Hb: {len(changed_cases)}")
display(changed_cases.head())