# -*- coding: utf-8 -*-
"""tieuduong_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5abNzPnMrEzhNPQnx1dlCuQcrEvigSL

# Dự đoán Bệnh Tiểu Đường (Diabetes Prediction)
Notebook này thực hiện đầu cuối một đường ống học máy (ML Pipeline) để đọc dữ liệu, phân tích khám phá (EDA), tiền xử lý, huấn luyện mô hình, và đánh giá.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

"""## 1. Đọc và khám phá dữ liệu ban đầu

"""

# Đọc file dữ liệu đã cung cấp
df = pd.read_csv('sample_data/tieuduong.csv')
print('Kích thước ban đầu:', df.shape)
df.head()

"""## 2. Xóa các biến theo yêu cầu (Cột Pregnancies)

"""

if 'Pregnancies' in df.columns:
    df = df.drop('Pregnancies', axis=1)
print('Kích thước dữ liệu sau khi xóa cột Pregnancies:', df.shape)
df.head()

"""## 3. Exploratory Data Analysis (EDA)

"""

# Tổng quan về dữ liệu và kiểu dữ liệu
df.info()
display(df.describe())

# Kiểm tra các giá trị khuyết thiếu (Null)
print('\nSố lượng NaN ban đầu:\n', df.isnull().sum())

# Phân phối của biến mục tiêu (Target outcome)
sns.countplot(x='Outcome', data=df)
plt.title('Phân phối biến mục tiêu (0: Không bị bệnh, 1: Có bệnh)')
plt.show()

# Ma trận tương quan giữa các đặc trưng (Features)
plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Ma trận tương quan')
plt.show()

"""## 4. Tiền xử lý dữ liệu (Preprocessing)

Trong dữ liệu tiểu đường, một số chỉ số sinh lý (Glucose, BloodPressure, SkinThickness, Insulin, BMI) không thể bằng 0. Giá trị 0 mang ý nghĩa là missing values.

"""

features_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

# Thay thế 0 bằng NaN để dễ dàng impute trung vị
df[features_with_zero] = df[features_with_zero].replace(0, np.nan)

# Điền giá trị nan bằng thông số trung vị (Median) phân định của mẫu đó
for col in features_with_zero:
    df[col].fillna(df[col].median(), inplace=True)

print('Đã xử lý xong giá trị 0 thành trung vị thành công. Kiểm tra lại missing values null/nan:')
print(df.isnull().sum())

# Tách đặc trưng (X) và biến mục tiêu dự đoán (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Chia dữ liệu 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standadization StandardScaler cho tập dữ liệu
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print('Kích thước tập Huấn Luyện (X_train):', X_train_scaled.shape)
print('Kích thước tập Kiểm Tra (X_test):', X_test_scaled.shape)

"""## 5. Huấn luyện mô hình (Model Training)

Chúng ta sẽ sử dụng Random Forest Classifier làm mô hình mẫu cơ bản để phân loại vì tính hiệu quả cao và dễ diễn giải.

"""

rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train_scaled, y_train)
print('Huấn luyện mô hình hoàn tất!')

"""## 6. Đánh giá (Evaluation)

Chúng ta tính Accurary, F1, Recall, Precision theo yêu cầu.

"""

# Thực hiện dự đoán trên tập test test
y_pred = rf_model.predict(X_test_scaled)

# Tính toán các metrics được yêu cầu
acc = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print('======== KẾT QUẢ ĐÁNH GIÁ MÔ HÌNH ========')
print(f'Accuracy (Độ chính xác) : {acc:.4f}')
print(f'Precision (Độ chuẩn xác) : {precision:.4f}')
print(f'Recall (Độ phủ/Độ nhạy): {recall:.4f}')
print(f'F1-Score               : {f1:.4f}')
print('===========================================')

# Báo cáo đánh giá chi tiết (Classification Report)
print('\nClassification Report:')
print(classification_report(y_test, y_pred))

# Confusion Matrix Diagram
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix')
plt.ylabel('Thực tế (True Label)')
plt.xlabel('Dự đoán (Predicted Label)')
plt.show()